### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jasonsturges**
Consistency and capitalization of new sentence.

### CODE REVIEW

**Comment by adzellman** [comment]
While you're updating this file, do you want to add your installation troubleshooting method?
```
sudo npm remove -g aemm
npm cache clean
sudo npm install -g aemm@latest
```

**Comment by jasonsturges** [comment]
Cool, let me see if I can unobtrusively fit a note in there.

**Comment by jasonsturges** [comment]
@adzellman I took a stab at it.  Hopefully it helps, or inspires a better way of including the note.

Thanks again for the help.

**Comment by adzellman** [comment]
Looks good.

**Pull request merged**
